name: Thirty Is What You Make It
favicon: null
layout_spectrum: 0.88721
typography_spectrum: 0.15087
title: Thirty is what you make it
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#54808b'
    - '#252757'
    - '#8fc5c7'
    - '#bb0800'
    - '#cc5302'
  brandStrength: 0.5625
  lightness: 0.3125
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
